[package]
name = "rumenu"
version = "0.1.0"
authors = ["JesÃºs Espino <jespinog@gmail.com>"]

[dependencies]
libc = "*"
getopts = "*"

[dependencies.x11]
path = "/home/jespino/Projects/Github/x11-rs/x11"
features = ["xlib"]
